// Modified from the plan_route plugin - Nelson Durrant, Nov 2025
// https://github.com/swri-robotics/mapviz/blob/ros2-devel/coug_gui.xml/src/plan_route_plugin.cpp

#ifndef MAPVIZ_PLUGINS__COUG_WAYPOINTS_PLUGIN_H_
#define MAPVIZ_PLUGINS__COUG_WAYPOINTS_PLUGIN_H_

#include <mapviz/mapviz_plugin.h>

// QT libraries
#include <QGLWidget>
#include <QObject>
#include <QWidget>

// ROS libraries
#include <rclcpp/rclcpp.hpp>
#include <tf2/transform_datatypes.hpp>

// Mapviz libraries
#include <mapviz/map_canvas.h>

// Messages
#include <geometry_msgs/msg/pose.hpp>
#include <geometry_msgs/msg/pose_array.hpp>

// C++ standard libraries
#include <string>
#include <vector>

// QT autogenerated files
#include "ui_coug_waypoints_config.h"

namespace coug_gui
{
class CougWaypointsPlugin : public mapviz::MapvizPlugin
{
  Q_OBJECT

  public:
  CougWaypointsPlugin();
  ~CougWaypointsPlugin() override;

  bool Initialize(QGLWidget* canvas) override;
  void Shutdown() override {}

  void Draw(double x, double y, double scale) override;
  void Paint(QPainter* painter, double x, double y, double scale) override;

  void Transform() override {};

  void LoadConfig(const YAML::Node& node, const std::string& path) override;
  void SaveConfig(YAML::Emitter& emitter, const std::string& path) override;

  QWidget* GetConfigWidget(QWidget* parent) override;

  bool SupportsPainting() override 
  { 
    return true; 
}

  protected:
  void PrintError(const std::string& message) override;
  void PrintInfo(const std::string& message) override;
  void PrintWarning(const std::string& message) override;
  bool eventFilter(QObject *object, QEvent* event) override;
  bool handleMousePress(QMouseEvent *);
  bool handleMouseRelease(QMouseEvent *);
  bool handleMouseMove(QMouseEvent *);

  protected Q_SLOTS:
  void PublishWaypoints();
  void Stop();
  void Clear();
  void VisibilityChanged(bool);
  void DepthChanged(double value);

  private:
  Ui::coug_waypoints_config ui_{};
  QWidget* config_widget_;
  mapviz::MapCanvas* map_canvas_;

  std::string waypoints_topic_;
  
  rclcpp::Publisher<geometry_msgs::msg::PoseArray>::SharedPtr waypoints_pub_;

  std::vector<geometry_msgs::msg::Pose> waypoints_;
  std::vector<geometry_msgs::msg::Pose> pub_waypoints_;

  int selected_point_;
  int dragged_point_; 
  bool is_mouse_down_;
  QPointF mouse_down_pos_;
  qint64 mouse_down_time_;
  
  qint64 max_ms_;
  qreal max_distance_;
};
}   // namespace coug_gui

#endif  // MAPVIZ_PLUGINS__COUG_WAYPOINTS_PLUGIN_H_
